# Generated by Django 4.1 on 2025-01-31 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='avatar',
            field=models.ImageField(help_text='最佳尺寸500*755', upload_to='team', verbose_name='头像'),
        ),
    ]
